name: Build Cloudflared ARM64

on:
  workflow_dispatch:

jobs:
  build:
    name: Build cloudflared for ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make

      - name: Build cloudflared
        run: |
          mkdir -p output
          GOARCH=arm64 GOOS=linux make cloudflared
          cp ./cloudflared ./output/cloudflared-arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloudflared-arm64
          path: ./output/cloudflared-arm64
